// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class AsicTxnFile
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public DateTime? Txndate { get; set; }
        public string Formdata { get; set; }
        public string AsicResponse { get; set; }
        public string TransStatus { get; set; }
        public string Ra56 { get; set; }
        public string Ra55 { get; set; }
        public string Acn { get; set; }
        public string DocumentNumber { get; set; }
        public string Datera55 { get; set; }
        public string Datera56 { get; set; }
        public string Companyname { get; set; }
    }
}