// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class AsicTxnStatus
    {
        public int Id { get; set; }
        public int? Companyid { get; set; }
        public DateTime? Txndate { get; set; }
        public int? Iserror { get; set; }
        public int? Istxnsuccess { get; set; }
        public int? Isaccepted { get; set; }
        public string Ra55data { get; set; }
        public string Ra56data { get; set; }
    }
}