// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Companysearch
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public DateTime? SearchOn { get; set; }
        public string Userid { get; set; }
        public string Status { get; set; }
        public string Fullname { get; set; }
        public string AsicStatus { get; set; }
        public string AsicError { get; set; }
        public string AsicFile { get; set; }
        public string AsicAcn { get; set; }
        public string AsicDocNo { get; set; }
        public string AsicResType { get; set; }
        public string Isship { get; set; }
        public string FullAddress { get; set; }
        public int? ShowStatus { get; set; }
        public long? Regid { get; set; }
        public string AsicOutFile { get; set; }
        public string Govofcomapany { get; set; }
    }
}