// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Lblmsg
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public string Sms { get; set; }
        public DateTime? Entrydate { get; set; }
    }
}