// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Lodgement
    {
        public int Id { get; set; }
        public string AsicRegisteredAgentNo { get; set; }
        public string Firm { get; set; }
        public string Contactname { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Postaladdress { get; set; }
        public string Suburb { get; set; }
        public string Stateterritory { get; set; }
        public string Postcode { get; set; }
    }
}