// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Ra55
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Acn { get; set; }
        public string CompanyType { get; set; }
        public string CompanyClass { get; set; }
        public string CertificatePrintOption { get; set; }
        public string JurisdictionOfRegistration { get; set; }
        public string DateOfRegistration { get; set; }
        public string CompanySubclass { get; set; }
        public string AccountNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAbn { get; set; }
        public string RegisteredAgentName { get; set; }
        public string RegisteredAgentAddress { get; set; }
        public string InvoiceDescription { get; set; }
        public string InvoiceAmmount { get; set; }
        public string DocumentNumber { get; set; }
        public string FormCode { get; set; }
        public string TaxInvoiceText { get; set; }
        public string TaxCode { get; set; }
        public string TaxAmmount { get; set; }
        public DateTime? Entrydate { get; set; }
    }
}