// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Ra56
    {
        public int Id { get; set; }
        public string ProposedCompanyName { get; set; }
        public string RequestDocumentNumber { get; set; }
        public string DateOfAdvice { get; set; }
        public string AsicadviceType { get; set; }
        public string AccountNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAbn { get; set; }
        public string RegisteredAgentName { get; set; }
        public string RegisteredAgentAddress { get; set; }
        public string InvoiceDescription { get; set; }
        public string InvoiceAmmount { get; set; }
        public string DocumentNumber { get; set; }
        public string FormCode { get; set; }
        public string TaxInvoiceText { get; set; }
        public string TaxCode { get; set; }
        public string TaxAmmount { get; set; }
        public string StatusText { get; set; }
        public DateTime? Entrydate { get; set; }
    }
}