// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Registration
    {
        public int Sno { get; set; }
        public string AgentSiteName { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string ProfileCategory { get; set; }
        public string Phone { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAbn { get; set; }
        public string UnitLevelSuits { get; set; }
        public string StreetNumberStreetName { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Fax { get; set; }
        public DateTime? Registrationdate { get; set; }
        public int? Isactive { get; set; }
        public string Website { get; set; }
        public string Logopath { get; set; }
    }
}