// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class ShareDistributeGrid
    {
        public int Id { get; set; }
        public string Linkid { get; set; }
        public string Sno { get; set; }
        public string Companyid { get; set; }
        public string Shareclass { get; set; }
        public decimal? Totalshares { get; set; }
        public decimal? Unitprice { get; set; }
        public decimal? Totalprice { get; set; }
        public decimal? CTotalshares { get; set; }
        public decimal? CAmountpaidpershare { get; set; }
        public decimal? CAmountremainingUnpaidpershare { get; set; }
        public decimal? CTotalamountpaidpershare { get; set; }
        public decimal? CTotalamountunpaidpershare { get; set; }
        public string CSharerange { get; set; }
        public string CCertificateno { get; set; }
        public DateTime? Entrydate { get; set; }
        public string IndividualOrCompany { get; set; }
    }
}