// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class ShareAllocate
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public string Shareclass { get; set; }
        public int? Totalshares { get; set; }
        public decimal? Unitprice { get; set; }
        public decimal? Totalprice { get; set; }
        public DateTime? Entrydate { get; set; }
        public int? Sno { get; set; }
    }
}