// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Step1
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public string Companyname { get; set; }
        public string CompanynameExt { get; set; }
        public string Stateterritorry { get; set; }
        public string Isspecialpurpose { get; set; }
        public string Isreservecompany410 { get; set; }
        public string Reservecompany410Asicnamereservationnumber { get; set; }
        public string Reservecompany410Fulllegalname { get; set; }
        public string Isproposeidentical { get; set; }
        public string ProposeidenticalBefore28may { get; set; }
        public string ProposeidenticalAfter28may { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno1 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory1 { get; set; }
        public string ProposeidenticalAfter28mayAbnnumber { get; set; }
        public string Isultimateholdingcompany { get; set; }
        public string UltimateholdingcompanyFulllegalname { get; set; }
        public string UltimateholdingcompanyCountry { get; set; }
        public string UltimateholdingcompanyAcnArbn { get; set; }
        public string UltimateholdingcompanyAbn { get; set; }
        public DateTime? Entrydate { get; set; }
        public string Acn { get; set; }
        public string Typeofcompany { get; set; }
        public string Classofcompany { get; set; }
        public string SpecialpurposeIfapplicable { get; set; }
        public string Cash { get; set; }
        public string Writtencontact { get; set; }
        public string IndivisualCompanyAsicForm401 { get; set; }
        public string CompanyNameAsicFrom401 { get; set; }
        public string CompanyActingAsTrustee { get; set; }
        public string ProposedNameYesNo { get; set; }
        public int? ProposeidenticalBefore28mayTotalstate { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno2 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory2 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno3 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory3 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno4 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory4 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno5 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory5 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno6 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory6 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno7 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory7 { get; set; }
        public string ProposeidenticalBefore28mayPreviousbusinessno8 { get; set; }
        public string ProposeidenticalBefore28mayPreviousstateteritory8 { get; set; }
        public string Openingtime { get; set; }
        public string Closingtime { get; set; }
        public bool? StandardHours { get; set; }
        public string TrusteeTrustname { get; set; }
        public string TrusteeAbn { get; set; }
        public string TrusteeTfn { get; set; }
        public string TrusteeAddress { get; set; }
        public string TrusteeCountry { get; set; }
        public string Companyusedfor { get; set; }
        public string Typeofuser { get; set; }
        public string UlimateHoldingCompany { get; set; }
        public string Ucompanyname { get; set; }
        public string Acnarbnabn { get; set; }
        public string CountryIcor { get; set; }
    }
}