// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Step4Anothershareholder
    {
        public int Id { get; set; }
        public int? Step4Id { get; set; }
        public string Companyid { get; set; }
        public string Shareholderdetails { get; set; }
        public string ShareclasstypeValue { get; set; }
        public string ShareclasstypeText { get; set; }
        public int? NoOfShares { get; set; }
        public decimal? Amountpaidpershare { get; set; }
        public decimal? Amountremainingunpaidpershare { get; set; }
        public string Isheldanotherorg { get; set; }
        public string Beneficialownername { get; set; }
        public string IndividualOrCompany { get; set; }
        public string IndividualOrCompanyName { get; set; }
        public string IndividualOrCompanyAddress { get; set; }
        public DateTime? Entrydate { get; set; }
        public string IndividualOrCompanyAcn { get; set; }
        public string IndividualOrCompanyDob { get; set; }
        public string IndividualOrCompanyUnitLevelSuite { get; set; }
        public string IndividualOrCompanyStreetNoName { get; set; }
        public string IndividualOrCompanySuburbTownCity { get; set; }
        public string IndividualOrCompanyState { get; set; }
        public string IndividualOrCompanyPostcode { get; set; }
        public string IndividualOrCompanyCountry { get; set; }
        public string Isjoint { get; set; }
        public string JointIndividualOrCompany { get; set; }
        public string JointIndividualOrCompanyName { get; set; }
        public string JointIndividualOrCompanyAcn { get; set; }
        public string JointIndividualOrCompanyDob { get; set; }
        public string JointIndividualOrCompanyUnitLevelSuite { get; set; }
        public string JointIndividualOrCompanyStreetNoName { get; set; }
        public string JointIndividualOrCompanySuburbTownCity { get; set; }
        public string JointIndividualOrCompanyState { get; set; }
        public string JointIndividualOrCompanyPostcode { get; set; }
        public string JointIndividualOrCompanyCountry { get; set; }
        public int? Dirid { get; set; }
        public string Placeofbirth { get; set; }
        public string Shareoption { get; set; }
        public string Sharedetailsnotheldanotherorg { get; set; }
    }
}