// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Step3
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public string Designation { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Familyname { get; set; }
        public string Anyformername { get; set; }
        public string FirstnameFormer { get; set; }
        public string MiddlenameFormer { get; set; }
        public string FamilynameFormer { get; set; }
        public string UnitLevelSuitePrimary { get; set; }
        public string StreetNoNamePrimary { get; set; }
        public string SuburbTownCityPrimary { get; set; }
        public string StatePrimary { get; set; }
        public string PostcodePrimary { get; set; }
        public string Country { get; set; }
        public string Dob { get; set; }
        public string Placeofbirth { get; set; }
        public string Countryofbirth { get; set; }
        public DateTime? Entrydate { get; set; }
        public string Isdirector { get; set; }
        public string Issecretary { get; set; }
        public string Ispublicofficer { get; set; }
    }
}