// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class Step2
    {
        public int Id { get; set; }
        public string Companyid { get; set; }
        public string Contactperson { get; set; }
        public string UnitLevelSuite { get; set; }
        public string StreetNoName { get; set; }
        public string SuburbTownCity { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Iscompanylocatedaboveaddress { get; set; }
        public string Isprimaryaddress { get; set; }
        public string ContactpersonPrimary { get; set; }
        public string UnitLevelSuitePrimary { get; set; }
        public string StreetNoNamePrimary { get; set; }
        public string SuburbTownCityPrimary { get; set; }
        public string StatePrimary { get; set; }
        public string PostcodePrimary { get; set; }
        public DateTime? Entrydate { get; set; }
        public string Occupiername { get; set; }
    }
}