// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblCompanyDirector
    {
        public long Id { get; set; }
        public long? CompanyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? Dobday { get; set; }
        public int? Dobmonth { get; set; }
        public int? Dobyear { get; set; }
        public string Dobcountry { get; set; }
        public string Dobstate { get; set; }
        public string Dobcity { get; set; }
        public string Dobaddress { get; set; }
        public DateTime? AddedDate { get; set; }
        public long? AddedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual TblCompany Company { get; set; }
    }
}