// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblCompanyShare
    {
        public long Id { get; set; }
        public long? CompanyId { get; set; }
        public long? DirectorId { get; set; }
        public string ShareClass { get; set; }
        public int? NoOfShare { get; set; }
        public double? ShareAmount { get; set; }
        public bool ShareBehalf { get; set; }
        public string OwnerName { get; set; }
        public DateTime? AddedDate { get; set; }
        public long? AddedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual TblCompany Company { get; set; }
        public virtual TblCompanyDirector Director { get; set; }
    }
}