// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblOption
    {
        public int Id { get; set; }
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
        public string Type { get; set; }
        public DateTime? AddedDate { get; set; }
        public int? AddedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? DeletedBy { get; set; }
        public bool? Del { get; set; }
    }
}