// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblTransaction
    {
        public long Id { get; set; }
        public bool? TransactionStatus { get; set; }
        public double? Amount { get; set; }
        public long? TrustCompanyId { get; set; }
        public string FormType { get; set; }
        public DateTime? AddedDate { get; set; }
        public long? AddedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public long? UpdatedBy { get; set; }
        public string TxnId { get; set; }
        public string FormName { get; set; }
    }
}