// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblTrustAppointer
    {
        public long Id { get; set; }
        public string HolderType { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAcn { get; set; }
        public bool? CommanSeal { get; set; }
        public string UnitLevel { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public string Suburb { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public bool? IsTrustee { get; set; }
        public string UnitType { get; set; }
        public int? UnitNumber { get; set; }
        public double? UnitTotalAmount { get; set; }
        public double? UnitAmountOwing { get; set; }
        public DateTime? AddedDate { get; set; }
        public long? AddedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public long? TrustId { get; set; }
        public DateTime? Dob { get; set; }
        public DateTime? CompanyRegDate { get; set; }
        public string ContactPersonName { get; set; }
    }
}