// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NextWave.Models
{
    public partial class TblUserMetum
    {
        public long Id { get; set; }
        public string MetaName { get; set; }
        public string MetaValue { get; set; }
        public long? UserId { get; set; }
        public DateTime? AddedDate { get; set; }
        public long? AddedBy { get; set; }

        public virtual TblUser User { get; set; }
    }
}